language: java

jdk:
    - oraclejdk8

notifications:
    email:
        - scm@after-sunrise.com

install:
  - gradle assemble -x signArchives -PossrhUsername="${ossrhUsername}" -PossrhPassword="${ossrhPassword}"
