language: java

jdk:
    - oraclejdk8

notifications:
    email:
        - scm@after-sunrise.com

install:
  - ./gradlew assemble -x signArchives

after_success:
  - ./gradlew jacocoTestReport coveralls
