language: java

jdk:
    - oraclejdk8

notifications:
    email:
        - scm@after-sunrise.com

before_script:
    - wget https://services.gradle.org/distributions/gradle-4.0.1-bin.zip
    - unzip gradle-4.0.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.0.1
    - export PATH=$GRADLE_HOME/bin:$PATH